"""empty message

Revision ID: 432ab366eaea
Revises: dbd805b1e09a
Create Date: 2024-09-25 11:19:32.917997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '432ab366eaea'
down_revision = 'dbd805b1e09a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('housekeeper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('housekeeper', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
