"""empty message

Revision ID: 44340fa03d0a
Revises: 432ab366eaea
Create Date: 2024-09-25 11:22:06.380989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44340fa03d0a'
down_revision = '432ab366eaea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
