"""empty message

Revision ID: 7348d5e8c8fe
Revises: dc481a112588
Create Date: 2024-09-25 14:08:54.318857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7348d5e8c8fe'
down_revision = 'dc481a112588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workinghours', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('workinghours')

    # ### end Alembic commands ###
