"""empty message

Revision ID: dc481a112588
Revises: e0000a73487c
Create Date: 2024-09-25 13:42:52.224768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc481a112588'
down_revision = 'e0000a73487c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('housekeeper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priceperhour', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('housekeeper', schema=None) as batch_op:
        batch_op.drop_column('priceperhour')

    # ### end Alembic commands ###
